title: This is My Title
author: Nicole (AUG2019)
email: aug2019@yopmail.com
description: > # this means to ignore newlines until "baseurl:"
  AUG2019 second GitHub Page.  Just a GitHub Learning Lab page.
  This was editing in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: ADD-TWITTER-LATER # DO NOT include the @ character, or else the build will fail!
github_username:  AUG2019 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
